name: vision_touch_ai
description: VisionTouch AI - prototype for visually impaired users.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0
  flutter_tts: ^3.5.0
  speech_to_text: ^7.3.0
  google_mlkit_text_recognition: ^0.7.0
  tflite_flutter: ^0.11.0
  vibration: ^1.7.4
  provider: ^6.0.5
  permission_handler: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
